name: Docker

on:
  release:
    types: [published]
    branches:
      - master
env:
  IMAGE_NAME: hhaluk/crypto-watchdog

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run:  docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push DockerHub
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION
          docker image ls
          docker image push $IMAGE_NAME:$VERSION
          docker image push $IMAGE_NAME:latest

        
